[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    madhephaestus/ESP32Encoder @ ^0.11.1
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/mathieucarbou/AsyncTCP.git
    https://github.com/mathieucarbou/ESPAsyncWebServer.git

board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed  = 921600

